# Generated by Django 5.0 on 2023-12-12 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nameofSIP', models.CharField(max_length=1024)),
                ('holderName', models.CharField(choices=[('Rajesh', 'Rajesh'), ('Rupesh', 'Rupesh'), ('Ranjana', 'Ranjana'), ('Ritesh', 'Ritesh')], max_length=1024)),
                ('sipAmount', models.FloatField()),
                ('dateOfRenewel', models.DateField()),
            ],
        ),
    ]
